version: '3'
services:
  database:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DATABASE=dev
  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025